services:
  hydra-server:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./data:/data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_CUSTOM_SERVER=true
